server:
  port: 80

spring:
  application:
    name: cloud-order-service

  cloud:
    consul:
      host: 192.168.2.107
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

payment:
  service:
    name: http://cloud-provider-payment
