server:
  port: 9527

spring:
  application:
    name: cloud-gateway

    #网关三大组件：路由（route），断言(predicate)，过滤器(filter)[单一，全局，自定义]
    #支持超时配置，日志，监控，跨域
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址，静态路由
          #uri: http://localhost:8001
          #动态路由
          uri: lb://cloud-payment-service

          #路由断言
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            # 时间格式为 java.time.ZonedDateTime
            - After=2020-06-07T22:05:27.651+08:00[Asia/Shanghai]
            - Before=2021-06-07T22:05:27.651+08:00[Asia/Shanghai]
            #cookie value使用正则匹配
            #- Cookie=chocolate, ch.p
            # 请求头 value使用正则匹配
            #- Header=X-Request-Id, \d+
            #- Host=**.somehost.org,**.anotherhost.org
            - Method=GET,POST
            #- Query=green
            #- RemoteAddr=192.168.2.1/24
            #- Weight=group1, 2

        - id: payment_route2 # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址，静态路由
          #uri: http://localhost:8001
          #动态路由
          uri: lb://cloud-payment-service
          #https://cloud.spring.io/spring-cloud-gateway/2.2.x/reference/html/#gateway-request-predicates-factories
          predicates:
            - Path=/payment/lb/** # 断言，路径相匹配的进行路由

        #- id: payment_route3
          #uri: http://localhost:8001
        #  uri: lb://cloud-payment-service
        #  predicates:
           # - Path=/payment/lb/** #断言,路径相匹配的进行路由
           # - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
          #- Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
          #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2