server:
  port: 8006

spring:
  application:
    name: cloud-payment-service

  cloud:
    consul:
      host: 192.168.2.107
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true